apiVersion: v1
kind: Namespace
metadata:
  name: yolo1
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: yolo-inference
  namespace: yolo1
  labels:
    app: yolo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: yolo
  template:
    metadata:
      labels:
        app: yolo
    spec:
      containers:
      - name: yolo
        # Custom image with Flask installed
        image: hamidhrf/yolo-flask:v1
        imagePullPolicy: IfNotPresent
        
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
        
        resources:
          limits:
            nvidia.com/gpu: 1
          requests:
            nvidia.com/gpu: 1
        
        env:
        - name: PYTHONUNBUFFERED
          value: "1"
        - name: YOLO_MODEL
          value: "yolov8x.pt"
        - name: YOLO_IMAGE_SIZE
          value: "1280"
        - name: YOLO_HALF
          value: "false"
        - name: CUDA_VISIBLE_DEVICES
          value: "0"
        
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 60
          periodSeconds: 10
        
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 50
          periodSeconds: 5
      runtimeClassName: nvidia
---
apiVersion: v1
kind: Service
metadata:
  name: yolo-api
  namespace: yolo1
  labels:
    app: yolo
spec:
  type: ClusterIP
  selector:
    app: yolo
  ports:
  - port: 8080
    targetPort: 8080
    protocol: TCP
    name: http
